# Generated by Django 4.0.3 on 2022-04-19 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('point_depart', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('altitude_depart', models.IntegerField(verbose_name='Altitude (m) ')),
                ('altitude_max', models.IntegerField(verbose_name='Altitude max (m) ')),
                ('altitude_min', models.IntegerField(verbose_name='Altitude min (m) ')),
                ('denivele_positif', models.IntegerField(verbose_name='Dénivelé positif (m) ')),
                ('denivele_negatif', models.IntegerField(verbose_name='Dénivelé négatif (m) ')),
                ('duree_estimee', models.FloatField(verbose_name='Durée (h) ')),
            ],
        ),
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(verbose_name='Niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateField(verbose_name='Date de sortie')),
                ('duree_reelle', models.FloatField(verbose_name='Durée réelle')),
                ('nombre_personne', models.IntegerField(verbose_name='Nombres de personnnes')),
                ('difficulte_ressentie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.niveau')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.experience')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('meteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.meteo')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itineraire',
            name='difficulte_estimee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.niveau'),
        ),
    ]
