# Generated by Django 4.0.4 on 2022-04-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix1', models.CharField(max_length=100)),
                ('choix2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sortie',
            name='experience',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='itineraires.experience'),
            preserve_default=False,
        ),
    ]
