# Generated by Django 4.0.4 on 2022-04-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_experience_sortie_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='choix1',
            new_name='choix',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='choix2',
        ),
    ]
