# Generated by Django 4.0.4 on 2022-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0003_rename_choix1_experience_choix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='sortie',
            name='nombre_personne',
            field=models.IntegerField(verbose_name='Nombres de personnnes'),
        ),
    ]
