# Generated by Django 4.0.4 on 2022-04-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0004_niveau_alter_sortie_nombre_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='difficulte_estimee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.niveau'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='niveau',
            field=models.IntegerField(verbose_name='Niveau'),
        ),
    ]
