# Generated by Django 4.0.4 on 2022-04-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0005_alter_itineraire_difficulte_estimee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sortie',
            name='difficulte_ressentie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='itineraires.niveau'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='meteo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='itineraires.meteo'),
            preserve_default=False,
        ),
    ]
