# Generated by Django 4.0.4 on 2022-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0007_sortie_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortie',
            name='data_sortie',
        ),
    ]
