# Generated by Django 4.0.4 on 2022-04-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_sortie_date_sortie'),
        ('itineraires', '0008_remove_sortie_data_sortie_sortie_date_sortie'),
    ]

    operations = [
    ]
